baseURL: https://nct-wakayama-college.github.io/ComputerClubWebsite/
languageCode: ja
title: 和歌山高専 コンピュータ部
# paginate: 12
theme: ["PaperMod", "hugo-embed-pdf-shortcode"]

# enableRobotsTXT: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false

# googleAnalytics: UA-123-45

# minify:
#   disableXML: true
#   minifyOutput: true

params:
#   env: production # to enable google analytics, opengraph, twitter-cards and schema.
#   title: ExampleSite
#   description: "ExampleSite description"
#   keywords: [Blog, Portfolio, PaperMod]
#   author: ["KashiuchiSotaro"] # multiple authors
#   images: ["<link or path of image for opengraph, twitter-cards>"]
#   DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  enableInlineShortcodes: true

  # homepage(toppage)
  mainSections: "posts"  
  homeInfoParams:
    Title: コンピュータ部へ ようこそ
    Content: "
      私達コンピュータ部は、和歌山工業高等専門学校(National College of Technology, Wakayama College)の情報系のクラブです。
      2024年度から本校の「ゆめくじら」というサークルと合併し、新体制で運営しています。動画、ゲーム、モデリング、イラスト、Webサイト、プログラミング等情報機器を使った幅広いものづくりをしています。
      このWebサイトでは日頃のコンピュータ部の活動を発信しています！
    "
  socialIcons: # optional
    - name: "youtube"
      url: "https://www.youtube.com/channel/UCpvPhDH-vLOFPqLt5M4B1Dg"
    - name: "github"
      url: "https://github.com/NIT-Wakayama-College"


outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

menus:
  main:
    - name: 私達について
      pageRef: /about
      weight: 10

    - name: 投稿
      pageRef: /posts
      weight: 20
    - name: 最近の投稿
      pageRef: /posts
      weight: 21
      parent: 投稿
    - name: お知らせ
      pageRef: /categories/news
      weight: 22
      parent: 投稿
    - name: ブログ
      pageRef: /categories/blog
      weight: 23
      parent: 投稿
    - name: タグ検索
      pageRef: /tags
      weight: 24
      parent: 投稿

    - name: 検索
      pageRef: /search
      weight: 60

    # - name: 作品紹介
    #   pageRef: /tags/prodcuts
    #   weight: 50

taxonomies:
  category: categories
  member-tag: members-tags
  tag: tags

# # Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#   highlight:
#     noClasses: false
#     # anchorLineNos: true
#     # codeFences: true
#     # guessSyntax: true
#     # lineNos: true
#     # style: monokai
